package com.mengka.springboot.dao.persistence;

import com.mengka.springboot.dao.domain.DeviceSensorDO;

public interface DeviceSensorDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sensor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sensor
     *
     * @mbg.generated
     */
    int insert(DeviceSensorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sensor
     *
     * @mbg.generated
     */
    int insertSelective(DeviceSensorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sensor
     *
     * @mbg.generated
     */
    DeviceSensorDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sensor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeviceSensorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sensor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeviceSensorDO record);
}