@startuml

participant 设备 as d1
participant IOT平台 as k1
participant iotapp
participant cabbage


cabbage -> iotapp: 创建设备
note right: 填写设备基本信息
activate iotapp
iotapp -> k1: 创建设备
activate k1
k1 --> iotapp: 200 OK响应


d1 -> d1: 设备上电

iotapp -> k1: 设置设备的制造商ID和型号
k1 --> iotapp: 204 No Content响应
iotapp --> cabbage: 200 OK响应

deactivate iotapp



d1 <-> k1: DTLS握手
activate d1
d1 -> k1: 注册（携带imei）
k1 -> k1: 检查imeis是否一致
k1 -> d1: 201 OK响应
deactivate k1
deactivate d1

@enduml