@startuml

participant 设备 as d1
participant IOT平台 as k1
participant iotapp


iotapp -> k1: 下发命令
activate iotapp
activate k1
k1 -> k1: 调用编解码库,\n对命令请求进行编码


k1 -> d1: 下发命令
activate d1

k1 --> iotapp: 200 OK响应\n更新命令状态为SEND
deactivate iotapp
d1 -> k1: ACK响应

k1 -> iotapp: 上报命令
activate iotapp
iotapp -> iotapp:更新命令状态

d1 -> k1: 205 Content响应
deactivate d1
deactivate iotapp
k1 -> k1: 调用编解码库,\n对命令响应进行解码

k1 -> iotapp: 上报命令执行结果
activate iotapp
iotapp -> iotapp: 更新命令状态
deactivate k1

@enduml