package com.mengka.springboot.dao.domain;

import java.util.Date;

public class BerthDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_berth.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_berth.PARK_ID
     *
     * @mbg.generated
     */
    private String parkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_berth.BERTH_CODE
     *
     * @mbg.generated
     */
    private String berthCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_berth.RODE_CODE
     *
     * @mbg.generated
     */
    private String rodeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_berth.TYPE
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_berth.MOVE_SWITCH
     *
     * @mbg.generated
     */
    private Integer moveSwitch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_berth.IS_VALID
     *
     * @mbg.generated
     */
    private Integer isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_berth.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_berth.UPDATED_BY
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_berth.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_berth.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_berth.ID
     *
     * @return the value of base_berth.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_berth.ID
     *
     * @param id the value for base_berth.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_berth.PARK_ID
     *
     * @return the value of base_berth.PARK_ID
     *
     * @mbg.generated
     */
    public String getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_berth.PARK_ID
     *
     * @param parkId the value for base_berth.PARK_ID
     *
     * @mbg.generated
     */
    public void setParkId(String parkId) {
        this.parkId = parkId == null ? null : parkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_berth.BERTH_CODE
     *
     * @return the value of base_berth.BERTH_CODE
     *
     * @mbg.generated
     */
    public String getBerthCode() {
        return berthCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_berth.BERTH_CODE
     *
     * @param berthCode the value for base_berth.BERTH_CODE
     *
     * @mbg.generated
     */
    public void setBerthCode(String berthCode) {
        this.berthCode = berthCode == null ? null : berthCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_berth.RODE_CODE
     *
     * @return the value of base_berth.RODE_CODE
     *
     * @mbg.generated
     */
    public String getRodeCode() {
        return rodeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_berth.RODE_CODE
     *
     * @param rodeCode the value for base_berth.RODE_CODE
     *
     * @mbg.generated
     */
    public void setRodeCode(String rodeCode) {
        this.rodeCode = rodeCode == null ? null : rodeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_berth.TYPE
     *
     * @return the value of base_berth.TYPE
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_berth.TYPE
     *
     * @param type the value for base_berth.TYPE
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_berth.MOVE_SWITCH
     *
     * @return the value of base_berth.MOVE_SWITCH
     *
     * @mbg.generated
     */
    public Integer getMoveSwitch() {
        return moveSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_berth.MOVE_SWITCH
     *
     * @param moveSwitch the value for base_berth.MOVE_SWITCH
     *
     * @mbg.generated
     */
    public void setMoveSwitch(Integer moveSwitch) {
        this.moveSwitch = moveSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_berth.IS_VALID
     *
     * @return the value of base_berth.IS_VALID
     *
     * @mbg.generated
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_berth.IS_VALID
     *
     * @param isValid the value for base_berth.IS_VALID
     *
     * @mbg.generated
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_berth.CREATED_BY
     *
     * @return the value of base_berth.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_berth.CREATED_BY
     *
     * @param createdBy the value for base_berth.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_berth.UPDATED_BY
     *
     * @return the value of base_berth.UPDATED_BY
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_berth.UPDATED_BY
     *
     * @param updatedBy the value for base_berth.UPDATED_BY
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_berth.CREATE_TIME
     *
     * @return the value of base_berth.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_berth.CREATE_TIME
     *
     * @param createTime the value for base_berth.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_berth.UPDATE_TIME
     *
     * @return the value of base_berth.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_berth.UPDATE_TIME
     *
     * @param updateTime the value for base_berth.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}