package com.mengka.springboot.dao.domain;

public class DeviceSensorDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_sensor.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_sensor.BERTH_ID
     *
     * @mbg.generated
     */
    private String berthId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_sensor.SENSOR_ADDR
     *
     * @mbg.generated
     */
    private String sensorAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_sensor.SENSOR_TYPE
     *
     * @mbg.generated
     */
    private Integer sensorType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_sensor.NET_ID
     *
     * @mbg.generated
     */
    private String netId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_sensor.ID
     *
     * @return the value of device_sensor.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_sensor.ID
     *
     * @param id the value for device_sensor.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_sensor.BERTH_ID
     *
     * @return the value of device_sensor.BERTH_ID
     *
     * @mbg.generated
     */
    public String getBerthId() {
        return berthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_sensor.BERTH_ID
     *
     * @param berthId the value for device_sensor.BERTH_ID
     *
     * @mbg.generated
     */
    public void setBerthId(String berthId) {
        this.berthId = berthId == null ? null : berthId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_sensor.SENSOR_ADDR
     *
     * @return the value of device_sensor.SENSOR_ADDR
     *
     * @mbg.generated
     */
    public String getSensorAddr() {
        return sensorAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_sensor.SENSOR_ADDR
     *
     * @param sensorAddr the value for device_sensor.SENSOR_ADDR
     *
     * @mbg.generated
     */
    public void setSensorAddr(String sensorAddr) {
        this.sensorAddr = sensorAddr == null ? null : sensorAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_sensor.SENSOR_TYPE
     *
     * @return the value of device_sensor.SENSOR_TYPE
     *
     * @mbg.generated
     */
    public Integer getSensorType() {
        return sensorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_sensor.SENSOR_TYPE
     *
     * @param sensorType the value for device_sensor.SENSOR_TYPE
     *
     * @mbg.generated
     */
    public void setSensorType(Integer sensorType) {
        this.sensorType = sensorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_sensor.NET_ID
     *
     * @return the value of device_sensor.NET_ID
     *
     * @mbg.generated
     */
    public String getNetId() {
        return netId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_sensor.NET_ID
     *
     * @param netId the value for device_sensor.NET_ID
     *
     * @mbg.generated
     */
    public void setNetId(String netId) {
        this.netId = netId == null ? null : netId.trim();
    }
}